name: LongViewSC_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-seurat
  - r-shinyjs
  - r-shinydashboard
  - r-plotly
  - r-heatmaply
  - r-viridis
  - r-sp
  - r-markdown
  - r-shiny
  - bioconductor-rtracklayer
  - r-devtools