name: LongViewSC_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base>=4.3
  - r-shiny
  - r-shinyjs
  - r-shinydashboard
  - r-seurat
  - r-ggplot2
  - r-plotly
  - r-heatmaply
  - r-dt
  - r-patchwork
  - r-tibble
  - r-dplyr
  - r-tidyr
  - r-scales
  - r-markdown
  - r-devtools
  - r-sortable
  - r-viridis
  - r-sp
  - bioconductor-rtracklayer
  - r-qs
  - r-qs2
  - pip
  - pip:
    - shinycssloaders
